# run configuration

n: 48  # number of time intervals per day
n_intervals: 50  # number of intervals in car factor transition matrix

n_rows: # number of rows to import xin each data file (limit numbers e.g. for debugging)
  gen: 1.e+6  # 172718543 all
  loads: 1.e+6  # 300267349 all
  car: 1.e+6  # 4449164 all

fill_type: # interpolate linearly to fill in errors instead of looking at day/week before
  gen: lin_interp
  loads: lin_interp

prob_test_filling_in: 0.01  # number between 0 and 1 ; what proportion of points we evaluate

n_cpu:  # to limit the number of CPUs being used

n_clus:
  loads: 4
  car: 3

data_types: ["car", "loads", "gen"] # ,
plots: True
do_test_filling_in: False
parallel: False
do_heat_map: True  # plot data available - this is computationally expensive
test_factor_distr: True
candidate_factor_distributions:
save_intermediate_outs: True
max_size_chunk: 1.e+7
